apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mcr.microsoft.com/oss/nginx/nginx:1.15.2-alpine
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: public-svc
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
  - name: testport
    nodePort: 32098
    port: 80
    protocol: TCP
    targetPort: 80
